Added query endpoint that takes in arguments and keeps ip as a global…
open-horizon-services/service-qr-code-generator pull request #7
Opened 2022-11-11 21:53 UTC by mahi-pas

… variable. It only gets edited when a new variable is submitted and persists on other queries.

Signed-off-by: Mahi <mahipasarkar@gmail.com>

2022-11-11 22:01 UTC, joewxboy requested changes
Great start, thanks!

Let's add one additional feature ... inspect the contents of the "ip" variable and ensure that it is in the form of a dotted quad: "xxx.xxx.xxx.xxx" where "xxx" is a number between 0 and 255.  If it isn't, then set it to null.

2022-12-06 22:08 UTC, mahi-pas commented
I have completed the change you asked for

2022-12-07 15:31 UTC, joewxboy approved these changes

2022-12-07 15:31 UTC, joewxboy commented on qr_code_generator/query.py
> +
Here I would expect you to have a conditional using .fullmatch() and a regular expression matching an IP address.  See https://www.golinuxcloud.com/python-pattern-matching/

2022-12-07 15:33 UTC, joewxboy commented
@mahi-pas Thanks, the code looks good.  According to the record above ^^^ three of your commits failed due to missing sign-off.  Are you able to go back and sign those, or should we just close this PR and re-submit a new one with the sign-offs?

2022-12-11 18:54 UTC, mahi-pas commented
> @mahi-pas Thanks, the code looks good. According to the record above ^^^ three of your commits failed due to missing sign-off. Are you able to go back and sign those, or should we just close this PR and re-submit a new one with the sign-offs?

I'll try a new pull request

2022-12-11 18:56 UTC, mahi-pas commented on qr_code_generator/query.py
> +
I chose the ipaddress class because it would be guaranteed to be correct. If you would like, I can change it. Should I revise it and use pattern matching?

2022-12-11 19:11 UTC, mahi-pas commented
It's in a new pull request: https://github.com/open-horizon-services/service-qr-code-generator/pull/10

2022-12-11 19:11 UTC, closed without merging